# Generated by Django 5.1.15 on 2026-08-18 18:28

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # apps.common.fields.CITextField renders as the `citext` type, which
        # SRS §7.5.1 specifies for user.email. The extension has to exist
        # before the first column that uses it.
        CITextExtension(),
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("code", models.CharField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=80)),
            ],
            options={
                "db_table": "role",
                "ordering": ["code"],
            },
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, editable=False, null=True),
                ),
                ("email", apps.common.fields.CITextField(unique=True)),
                (
                    "phone_e164",
                    models.CharField(blank=True, default=None, max_length=20, null=True),
                ),
                ("password", models.CharField(db_column="password_hash", max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending verification"),
                            ("ACTIVE", "Active"),
                            ("SUSPENDED", "Suspended"),
                            ("CLOSED", "Closed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("email_verified_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("phone_verified_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("mfa_secret", models.BinaryField(blank=True, default=None, null=True)),
                ("mfa_enrolled_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("failed_login_count", models.SmallIntegerField(default=0)),
                ("locked_until", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "failed_login_window_started_at",
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ("lockout_count", models.IntegerField(default=0)),
                (
                    "last_login",
                    models.DateTimeField(blank=True, db_column="last_login_at", null=True),
                ),
            ],
            options={
                "db_table": "user",
                "indexes": [models.Index(fields=["status"], name="user_status_idx")],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("email",),
                        name="user_email_unique_alive",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True), ("phone_e164__isnull", False)
                        ),
                        fields=("phone_e164",),
                        name="user_phone_unique_alive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TouristProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=80)),
                ("last_name", models.CharField(max_length=80)),
                (
                    "nationality",
                    models.CharField(blank=True, default=None, max_length=2, null=True),
                ),
                ("date_of_birth", models.DateField(blank=True, default=None, null=True)),
                ("passport_reference", models.BinaryField(blank=True, default=None, null=True)),
                ("emergency_contact", models.JSONField(blank=True, default=None, null=True)),
                ("locale", models.CharField(default="en", max_length=10)),
                ("preferred_currency", models.CharField(default="USD", max_length=3)),
                ("interest_tags", models.JSONField(blank=True, default=list)),
                ("marketing_opt_in", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tourist_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "tourist_profile",
            },
        ),
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[("IOS", "iOS"), ("ANDROID", "Android"), ("WEB", "Web")],
                        max_length=10,
                    ),
                ),
                ("push_token", models.CharField(max_length=512)),
                ("device_name", models.CharField(blank=True, default="", max_length=120)),
                ("app_version", models.CharField(blank=True, default="", max_length=32)),
                ("last_seen_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("revoked_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "device",
                "indexes": [
                    models.Index(fields=["user", "-last_seen_at"], name="device_user_seen_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=("push_token",),
                        name="device_push_token_unique_live",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OneTimeToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("EMAIL_VERIFICATION", "Email verification"),
                            ("PASSWORD_RESET", "Password reset"),
                        ],
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("consumed_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="one_time_tokens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "one_time_token",
                "indexes": [
                    models.Index(
                        fields=["user", "purpose", "-created_at"], name="ott_user_purpose_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("jti", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("family_id", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ("issued_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("revoked_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("superseded_by", models.UUIDField(blank=True, default=None, null=True)),
                ("ip", models.GenericIPAddressField(blank=True, default=None, null=True)),
                ("user_agent", models.CharField(blank=True, default="", max_length=400)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "session",
                "indexes": [
                    models.Index(fields=["user", "-issued_at"], name="session_user_time_idx"),
                    models.Index(
                        condition=models.Q(("revoked_at__isnull", True)),
                        fields=["expires_at"],
                        name="session_live_expiry_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserRole",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("granted_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "granted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_granted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="user_roles",
                        to="identity.role",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_role",
                "constraints": [
                    models.UniqueConstraint(fields=("user", "role"), name="user_role_unique")
                ],
            },
        ),
    ]
