# Generated by Django 5.1.15 on 2026-08-18 18:38

from django.db import migrations

import apps.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0002_updated_at_triggers_and_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="email",
            field=apps.common.fields.CITextField(),
        ),
    ]
