# Generated by Django 5.1.15 on 2026-09-01 10:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("identity", "0003_drop_unconditional_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="onetimetoken",
            name="attempts",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="onetimetoken",
            name="purpose",
            field=models.CharField(
                choices=[
                    ("EMAIL_VERIFICATION", "Email verification"),
                    ("EMAIL_VERIFICATION_CODE", "Email verification code"),
                    ("PASSWORD_RESET", "Password reset"),
                ],
                max_length=32,
            ),
        ),
    ]
