"""finance's five tables — §7.5.14, §22.2 to §22.5, ADR 0028.

`ledger_entry` is the only one the SRS specifies, and ADR 0028 records why the
specification is not enough: no account column, no journal id, and every
reference nullable while BR-064 reconciles per booking. The other four are
designed there too.

**The ledger is append-only in the database.** §7.5.14 asks for UPDATE and
DELETE to be revoked at the role level; this is the row-level equivalent, and
it is the same trigger `booking_status_history`, `payment_transaction` and
`payment_webhook_event` already carry. A correction is a new entry naming
`reversal_of_id` (BR-077).

`fx_rate` is deliberately not created — nothing on the paying path converts
(ADR 0024), and a table with no writer is a promise rather than a record.
"""

# Generated by Django 5.1.15 on 2026-09-21 19:05

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.common.db import attach_updated_at_trigger

APPEND_ONLY_SQL = """
CREATE OR REPLACE FUNCTION ledger_entry_is_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION
        'ledger_entry is append-only (SRS 7.5.14, BR-077): % refused. '
        'A correction is a new entry naming reversal_of_id.', TG_OP;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS ledger_entry_append_only ON ledger_entry;
CREATE TRIGGER ledger_entry_append_only
    BEFORE UPDATE OR DELETE ON ledger_entry
    FOR EACH ROW EXECUTE FUNCTION ledger_entry_is_append_only();
"""

DROP_APPEND_ONLY_SQL = """
DROP TRIGGER IF EXISTS ledger_entry_append_only ON ledger_entry;
DROP FUNCTION IF EXISTS ledger_entry_is_append_only();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommissionRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("LISTING", "One listing"),
                            ("PROVIDER", "One provider"),
                            ("TYPE", "A booking type"),
                            ("GLOBAL", "Everything"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "listing_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "provider_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                ("booking_type", models.CharField(blank=True, default="", max_length=20)),
                ("priority", models.IntegerField(default=0)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("PERCENT", "A percentage of gross"),
                            ("FLAT", "A fixed amount"),
                            ("TIERED", "Bands over the provider's monthly volume"),
                        ],
                        default="PERCENT",
                        max_length=20,
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=5, null=True
                    ),
                ),
                (
                    "flat_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                ("tiers", models.JSONField(blank=True, default=list)),
                (
                    "min_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "max_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("valid_from", models.DateField(blank=True, default=None, null=True)),
                ("valid_to", models.DateField(blank=True, default=None, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "commission_rule",
                "ordering": ["-priority", "id"],
                "indexes": [
                    models.Index(fields=["scope", "is_active"], name="commission_scope_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("scope__in", ["LISTING", "PROVIDER", "TYPE", "GLOBAL"])
                        ),
                        name="commission_scope_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("method__in", ["PERCENT", "FLAT", "TIERED"])),
                        name="commission_method_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("method", "PERCENT"), _negated=True),
                            ("percent__isnull", False),
                            _connector="OR",
                        ),
                        name="commission_percent_has_a_percent",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("method", "FLAT"), _negated=True),
                            ("flat_amount__isnull", False),
                            _connector="OR",
                        ),
                        name="commission_flat_has_an_amount",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("percent__isnull", True),
                            models.Q(("percent__gte", 0), ("percent__lte", 100)),
                            _connector="OR",
                        ),
                        name="commission_percent_is_a_percentage",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("account", models.CharField(db_index=True, max_length=30)),
                ("journal_id", models.UUIDField(db_index=True)),
                ("entry_type", models.CharField(max_length=30)),
                ("direction", models.CharField(max_length=6)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "booking_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "payment_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "provider_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "payout_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                ("reversal_of_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("memo", models.CharField(blank=True, default="", max_length=200)),
                ("occurred_at", models.DateTimeField()),
            ],
            options={
                "db_table": "ledger_entry",
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["provider_id", "currency", "occurred_at"],
                        name="ledger_statement_idx",
                    ),
                    models.Index(fields=["booking_id"], name="ledger_booking_idx"),
                    models.Index(fields=["account", "occurred_at"], name="ledger_account_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="ledger_amount_is_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("direction__in", ["DEBIT", "CREDIT"])),
                        name="ledger_direction_is_known",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("booking_id__isnull", False)),
                        fields=("booking_id", "entry_type"),
                        name="ledger_one_entry_per_booking_and_type",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Payout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("provider_id", models.BigIntegerField(db_index=True)),
                ("currency", models.CharField(max_length=3)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Assembled, awaiting approval"),
                            ("APPROVED", "Approved by finance"),
                            ("PAID", "Released"),
                            ("FAILED", "Release failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                (
                    "approved_by_user_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                ("approved_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("rail_reference", models.CharField(blank=True, default="", max_length=120)),
                ("paid_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("failure_reason", models.CharField(blank=True, default="", max_length=500)),
            ],
            options={
                "db_table": "payout",
                "ordering": ["-period_end", "provider_id"],
                "indexes": [
                    models.Index(
                        fields=["provider_id", "status"], name="payout_provider_status_idx"
                    ),
                    models.Index(fields=["status", "period_end"], name="payout_worklist_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="payout_amount_is_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["DRAFT", "APPROVED", "PAID", "FAILED"])),
                        name="payout_status_is_known",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("status", "FAILED"), _negated=True),
                        fields=("provider_id", "currency", "period_end"),
                        name="one_live_payout_per_provider_period",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("period_end__gte", models.F("period_start"))),
                        name="payout_period_ends_after_it_starts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ProviderBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("provider_id", models.BigIntegerField(db_index=True)),
                ("currency", models.CharField(max_length=3)),
                ("pending_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                (
                    "available_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
            ],
            options={
                "db_table": "provider_balance",
                "ordering": ["provider_id", "currency"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("provider_id", "currency"),
                        name="one_balance_per_provider_and_currency",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PayoutItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("booking_id", models.BigIntegerField(db_index=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("memo", models.CharField(blank=True, default="", max_length=200)),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="finance.payout",
                    ),
                ),
            ],
            options={
                "db_table": "payout_item",
                "ordering": ["payout_id", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("payout", "booking_id"), name="one_item_per_booking_and_payout"
                    )
                ],
            },
        ),
        attach_updated_at_trigger("commission_rule"),
        attach_updated_at_trigger("provider_balance"),
        attach_updated_at_trigger("payout"),
        migrations.RunSQL(APPEND_ONLY_SQL, DROP_APPEND_ONLY_SQL),
    ]
