"""Where a driver was — §13, §7.6, ADR 0029.

This module's first migration, in Phase 9a, and it creates one of the three
tables §6.4 assigns here. `geofence` and `route_cache` are deliberately absent;
the models docstring says why for each, and ADR 0029 records it.

The composite index is §7.6's "time-series scan": `(driver_id, recorded_at
DESC)` is what makes §11.6's anchor lookup one row per driver rather than a
sort of everything they have ever reported. The GiST index on `point` is the
"proximity" half of the same line, and Phase 10's fan-out is what will use it.

No partitioning. §7.6 wants this table partitioned daily and §31.5 gives it a
30-day retention; both are Phase 10's, where there is an access pattern to
design against rather than a guess at one.
"""

# Generated by Django 5.1.15 on 2026-09-27 17:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DriverLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("driver_id", models.BigIntegerField()),
                (
                    "point",
                    django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326),
                ),
                ("accuracy_m", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "speed_kph",
                    models.DecimalField(
                        blank=True, decimal_places=1, default=None, max_digits=5, null=True
                    ),
                ),
                ("heading", models.SmallIntegerField(blank=True, default=None, null=True)),
                ("recorded_at", models.DateTimeField(db_index=True)),
                ("received_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "driver_location",
                "indexes": [
                    models.Index(
                        fields=["driver_id", "-recorded_at"], name="driver_location_latest_idx"
                    ),
                    models.Index(fields=["point"], name="driver_location_point_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("accuracy_m__isnull", True), ("accuracy_m__gte", 0), _connector="OR"
                        ),
                        name="driver_location_accuracy_non_negative",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("heading__isnull", True),
                            models.Q(("heading__gte", 0), ("heading__lte", 359)),
                            _connector="OR",
                        ),
                        name="driver_location_heading_is_a_bearing",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("speed_kph__isnull", True), ("speed_kph__gte", 0), _connector="OR"
                        ),
                        name="driver_location_speed_non_negative",
                    ),
                ],
            },
        ),
    ]
