"""payment's four tables — §7.5.13 and ADR 0027.

Only `payment` has a specification in the SRS. The other three are designed in
ADR 0027 against §7.2's conventions, and every column the SRS does not name is
recorded there rather than appearing here without explanation.

**Two tables are append-only in the database.** §7.7 lists immutability as a
database mechanism, and the reason is the same one R26 gives for booking
history: an application promise not to UPDATE erodes one "just this once"
correction at a time. `payment_transaction` is the platform's account of what
it did; `payment_webhook_event` is the PSP's own words. Both are evidence in a
dispute, and evidence somebody can edit afterwards is not evidence.

The triggers refuse UPDATE *and* DELETE, which also means a payment carrying
either cannot be deleted at all — the ORM cascades row by row in Python, so the
refusal reaches it. That is §7.2's "financial records are never deleted",
enforced rather than hoped for. Test databases roll back or TRUNCATE, and
neither fires a row trigger.
"""

# Generated by Django 5.1.15 on 2026-09-15 20:33

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.common.db import attach_updated_at_trigger


def _append_only(table: str, rule: str) -> str:
    return f"""
CREATE OR REPLACE FUNCTION {table}_is_append_only() RETURNS trigger AS $$
BEGIN
    RAISE EXCEPTION '{table} is append-only ({rule}): % refused', TG_OP;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS {table}_append_only ON {table};
CREATE TRIGGER {table}_append_only
    BEFORE UPDATE OR DELETE ON {table}
    FOR EACH ROW EXECUTE FUNCTION {table}_is_append_only();
"""


def _drop_append_only(table: str) -> str:
    return f"""
DROP TRIGGER IF EXISTS {table}_append_only ON {table};
DROP FUNCTION IF EXISTS {table}_is_append_only();
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("version", models.IntegerField(default=0, editable=False)),
                ("trip_id", models.BigIntegerField(db_index=True)),
                ("tourist_id", models.BigIntegerField(db_index=True)),
                (
                    "method",
                    models.CharField(
                        choices=[("CARD", "Card"), ("MOBILE_MONEY", "Mobile money")], max_length=20
                    ),
                ),
                ("presentment_currency", models.CharField(max_length=3)),
                ("presentment_amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("settlement_currency", models.CharField(max_length=3)),
                (
                    "settlement_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "fx_rate",
                    models.DecimalField(
                        blank=True, decimal_places=8, default=None, max_digits=18, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "Initiated"),
                            ("PENDING", "Pending"),
                            ("AUTHORISED", "Authorised"),
                            ("CAPTURED", "Captured"),
                            ("PARTIALLY_REFUNDED", "Partially refunded"),
                            ("REFUNDED", "Refunded"),
                            ("FAILED", "Failed"),
                            ("EXPIRED", "Expired"),
                            ("DISPUTED", "Disputed"),
                            ("CHARGEBACK_LOST", "Chargeback lost"),
                        ],
                        default="INITIATED",
                        max_length=20,
                    ),
                ),
                ("psp_name", models.CharField(max_length=40)),
                (
                    "psp_reference",
                    models.CharField(
                        blank=True, db_index=True, default=None, max_length=120, null=True
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("failure_code", models.CharField(blank=True, default="", max_length=40)),
                (
                    "payment_instrument_summary",
                    models.JSONField(blank=True, default=None, null=True),
                ),
                ("expires_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("authorised_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("captured_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "payment",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["trip_id", "status"], name="payment_trip_status_idx"),
                    models.Index(fields=["tourist_id", "-created_at"], name="payment_tourist_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("psp_reference__isnull", False)),
                        fields=("psp_reference",),
                        name="payment_psp_reference_unique",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "INITIATED",
                                    "PENDING",
                                    "AUTHORISED",
                                    "CAPTURED",
                                    "PARTIALLY_REFUNDED",
                                    "DISPUTED",
                                ],
                            )
                        ),
                        fields=("trip_id",),
                        name="payment_one_live_per_trip",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "INITIATED",
                                    "PENDING",
                                    "AUTHORISED",
                                    "CAPTURED",
                                    "PARTIALLY_REFUNDED",
                                    "REFUNDED",
                                    "FAILED",
                                    "EXPIRED",
                                    "DISPUTED",
                                    "CHARGEBACK_LOST",
                                ],
                            )
                        ),
                        name="payment_status_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("method__in", ["CARD", "MOBILE_MONEY"])),
                        name="payment_method_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("presentment_amount__gt", 0)),
                        name="payment_amount_is_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentWebhookEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("psp_name", models.CharField(max_length=40)),
                ("psp_event_id", models.CharField(max_length=120, unique=True)),
                ("event_type", models.CharField(max_length=80)),
                (
                    "psp_reference",
                    models.CharField(blank=True, db_index=True, default="", max_length=120),
                ),
                ("payload", models.JSONField()),
                ("signature_verified", models.BooleanField(default=False)),
                (
                    "payment_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("RECEIVED", "Received, not yet processed"),
                            ("APPLIED", "Applied"),
                            ("DUPLICATE", "Duplicate event id"),
                            ("IGNORED_NOT_ADVANCING", "Ignored: would not advance the state"),
                            ("UNMATCHED", "No payment for this reference"),
                        ],
                        default="RECEIVED",
                        max_length=30,
                    ),
                ),
                ("note", models.CharField(blank=True, default="", max_length=500)),
                ("received_at", models.DateTimeField()),
                ("processed_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "payment_webhook_event",
                "ordering": ["-received_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["psp_name", "received_at"], name="webhook_event_arrival_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "outcome__in",
                                [
                                    "RECEIVED",
                                    "APPLIED",
                                    "DUPLICATE",
                                    "IGNORED_NOT_ADVANCING",
                                    "UNMATCHED",
                                ],
                            )
                        ),
                        name="webhook_outcome_is_known",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "from_status",
                    models.CharField(blank=True, default=None, max_length=20, null=True),
                ),
                ("to_status", models.CharField(max_length=20)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default="", max_length=3)),
                ("failure_code", models.CharField(blank=True, default="", max_length=40)),
                ("psp_reference", models.CharField(blank=True, default="", max_length=120)),
                ("raw_event_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("actor_role", models.CharField(max_length=40)),
                ("actor_user_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                ("occurred_at", models.DateTimeField()),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="payment.payment",
                    ),
                ),
            ],
            options={
                "db_table": "payment_transaction",
                "ordering": ["occurred_at", "id"],
                "indexes": [
                    models.Index(fields=["payment", "occurred_at"], name="payment_txn_idx")
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("actor_role", ""), _negated=True),
                        name="payment_txn_names_an_actor",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Refund",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "booking_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("currency", models.CharField(max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("SETTLED", "Settled"),
                            ("FAILED", "Failed"),
                        ],
                        default="REQUESTED",
                        max_length=20,
                    ),
                ),
                ("reason_code", models.CharField(max_length=40)),
                ("reason", models.CharField(blank=True, default="", max_length=500)),
                (
                    "requested_by_user_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "approved_by_user_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                ("psp_refund_reference", models.CharField(blank=True, default="", max_length=120)),
                ("failure_code", models.CharField(blank=True, default="", max_length=40)),
                ("idempotency_key", models.CharField(max_length=64, unique=True)),
                ("requested_at", models.DateTimeField()),
                ("settled_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refunds",
                        to="payment.payment",
                    ),
                ),
            ],
            options={
                "db_table": "refund",
                "ordering": ["-requested_at", "id"],
                "indexes": [
                    models.Index(fields=["payment", "status"], name="refund_payment_status_idx"),
                    models.Index(fields=["status", "requested_at"], name="refund_worklist_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)), name="refund_amount_is_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("status__in", ["REQUESTED", "SETTLED", "FAILED"])),
                        name="refund_status_is_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("settled_at__isnull", False), ("status", "SETTLED")),
                            models.Q(("status", "SETTLED"), _negated=True),
                            _connector="OR",
                        ),
                        name="refund_settled_has_a_time",
                    ),
                ],
            },
        ),
        attach_updated_at_trigger("payment"),
        attach_updated_at_trigger("refund"),
        migrations.RunSQL(
            _append_only("payment_transaction", "SRS PM6"),
            _drop_append_only("payment_transaction"),
        ),
        migrations.RunSQL(
            _append_only("payment_webhook_event", "SRS §21.5"),
            _drop_append_only("payment_webhook_event"),
        ),
    ]
