# Generated by Django 5.1.15 on 2026-09-21 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payment", "0003_settle_refunds_runs_every_minute"),
    ]

    operations = [
        migrations.AddField(
            model_name="refund",
            name="provider_compensation",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
    ]
