"""The trip planner's four tables — SRS §7.5.10, §7.5.11, §7.3 ERD, §10.

Schema only. Nothing writes a trip yet; the constraints ship with the tables so
that the invariants the planner must respect are in the database before the
first writer exists rather than in a reviewer's memory. That ordering is what
made §7.5.11's "a CHECK per item_type" worth writing as five separate named
constraints: when the sequencer starts producing rows, a malformed one names
the item type it got wrong.

The references into `identity`, `catalogue` and `inventory` are plain integers
in the model (ADR 0012) and FOREIGN KEYs here. A migration may say what a model
may not, because a migration dependency is a string and not an import — the
database keeps its integrity and the module keeps its seam.

`itinerary_item.booking_id` is the one reference with no key yet. `booking`
arrives in Phase 7, and until it does there is nothing to point at; the column
is nullable, nothing writes it, and the constraint lands with the table it
references. That is ADR 0012's own arrangement for `accommodation.provider_id`,
applied to the one case here that has not yet caught up.
"""

# Generated by Django 5.1.15 on 2026-08-30 10:17

import uuid

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.db.models.expressions
import django.utils.timezone
from django.db import migrations, models

import apps.trip.validators
from apps.common.db import attach_updated_at_trigger

TABLES = ["trip", "itinerary", "itinerary_item", "trip_flight"]

#: RESTRICT rather than CASCADE throughout. A destination or an activity with a
#: planned trip against it must not be deletable out from under the trip — and
#: none of these parents is soft-deletable-only, so a hard delete is reachable
#: from a shell. §7.2 keeps trips out of the soft-delete set precisely because a
#: journey somebody planned is a record, so nothing here may vanish silently.
FOREIGN_KEYS = """
ALTER TABLE trip
    ADD CONSTRAINT trip_tourist_fk
    FOREIGN KEY (tourist_id) REFERENCES tourist_profile(id);

ALTER TABLE trip
    ADD CONSTRAINT trip_destination_fk
    FOREIGN KEY (destination_id) REFERENCES destination(id);

ALTER TABLE trip_flight
    ADD CONSTRAINT trip_flight_gateway_destination_fk
    FOREIGN KEY (gateway_destination_id) REFERENCES destination(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_accommodation_fk
    FOREIGN KEY (accommodation_id) REFERENCES accommodation(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_activity_fk
    FOREIGN KEY (activity_id) REFERENCES activity(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_activity_departure_fk
    FOREIGN KEY (activity_departure_id) REFERENCES activity_departure(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_attraction_fk
    FOREIGN KEY (attraction_id) REFERENCES attraction(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_origin_destination_fk
    FOREIGN KEY (origin_destination_id) REFERENCES destination(id);

ALTER TABLE itinerary_item
    ADD CONSTRAINT itinerary_item_target_destination_fk
    FOREIGN KEY (target_destination_id) REFERENCES destination(id);
"""

DROP_FOREIGN_KEYS = """
ALTER TABLE trip DROP CONSTRAINT IF EXISTS trip_tourist_fk;
ALTER TABLE trip DROP CONSTRAINT IF EXISTS trip_destination_fk;
ALTER TABLE trip_flight DROP CONSTRAINT IF EXISTS trip_flight_gateway_destination_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_accommodation_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_activity_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_activity_departure_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_attraction_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_origin_destination_fk;
ALTER TABLE itinerary_item DROP CONSTRAINT IF EXISTS itinerary_item_target_destination_fk;
"""


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        # By name, not by import. Each owns a table the keys below
        # reference, and must have created it first.
        ("identity", "0003_drop_unconditional_email_unique"),
        ("catalogue", "0010_media_market_owner"),
        ("inventory", "0002_room_availability_deferred_to_v2"),
        ("common", "0003_updated_at_uses_the_wall_clock"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("version", models.IntegerField(default=0, editable=False)),
                ("reference", models.CharField(editable=False, max_length=20, unique=True)),
                ("tourist_id", models.BigIntegerField(db_index=True)),
                ("destination_id", models.BigIntegerField(db_index=True)),
                ("title", models.CharField(blank=True, default=None, max_length=140, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("infants", models.PositiveSmallIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("PRICED", "Priced"),
                            ("PENDING_PAYMENT", "Pending payment"),
                            ("CONFIRMED", "Confirmed"),
                            ("IN_PROGRESS", "In progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        max_length=3, validators=[apps.trip.validators.validate_iso_currency_code]
                    ),
                ),
                (
                    "subtotal_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=14),
                ),
                ("fee_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("tax_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("total_amount", models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ("priced_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("quote_expires_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, default=None, null=True)),
            ],
            options={
                "db_table": "trip",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["tourist_id", "status"], name="trip_tourist_status_idx"),
                    models.Index(
                        fields=["status", "quote_expires_at"], name="trip_quote_expiry_idx"
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("end_date__gte", models.F("start_date"))),
                        name="trip_end_date_not_before_start",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("adults__gte", 1)), name="trip_has_at_least_one_adult"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "total_amount",
                                django.db.models.expressions.CombinedExpression(
                                    django.db.models.expressions.CombinedExpression(
                                        models.F("subtotal_amount"), "+", models.F("fee_amount")
                                    ),
                                    "+",
                                    models.F("tax_amount"),
                                ),
                            )
                        ),
                        name="trip_total_is_the_sum_of_its_parts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Itinerary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("version", models.IntegerField(default=1)),
                ("generated_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "validation_state",
                    models.CharField(
                        choices=[
                            ("NOT_VALIDATED", "Not validated"),
                            ("VALID", "Valid"),
                            ("WARNINGS", "Warnings only"),
                            ("ERRORS", "Errors"),
                        ],
                        default="NOT_VALIDATED",
                        max_length=20,
                    ),
                ),
                ("total_distance_m", models.IntegerField(blank=True, default=None, null=True)),
                ("total_travel_seconds", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "trip",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="itinerary",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "db_table": "itinerary",
            },
        ),
        migrations.CreateModel(
            name="TripFlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[("INBOUND", "Inbound"), ("OUTBOUND", "Outbound")], max_length=10
                    ),
                ),
                ("flight_number", models.CharField(max_length=10)),
                ("airline_iata", models.CharField(max_length=3)),
                ("gateway_destination_id", models.BigIntegerField(db_index=True)),
                ("scheduled_at", models.DateTimeField()),
                ("actual_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("terminal", models.CharField(blank=True, default=None, max_length=20, null=True)),
                ("pax_count", models.PositiveSmallIntegerField()),
                ("luggage_count", models.PositiveSmallIntegerField(default=0)),
                (
                    "trip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flights",
                        to="trip.trip",
                    ),
                ),
            ],
            options={
                "db_table": "trip_flight",
                "ordering": ["direction"],
            },
        ),
        migrations.CreateModel(
            name="ItineraryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("sequence_no", models.PositiveSmallIntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("STAY", "Stay"),
                            ("ACTIVITY", "Activity"),
                            ("TRANSFER", "Transfer"),
                            ("ATTRACTION", "Attraction"),
                            ("FREE_TIME", "Free time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("accommodation_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("activity_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "activity_departure_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                ("attraction_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "origin_destination_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "target_destination_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "location_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "origin_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "target_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                ("distance_m", models.IntegerField(blank=True, default=None, null=True)),
                ("travel_seconds", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "estimate_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROUTED", "Routed"),
                            ("MATRIX", "Matrix"),
                            ("APPROXIMATE", "Approximate"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "pax_count",
                    models.PositiveSmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        blank=True,
                        default=None,
                        max_length=3,
                        null=True,
                        validators=[apps.trip.validators.validate_iso_currency_code],
                    ),
                ),
                ("booking_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="trip.itinerary",
                    ),
                ),
            ],
            options={
                "db_table": "itinerary_item",
                "ordering": ["day_number", "sequence_no"],
                "indexes": [
                    models.Index(fields=["itinerary", "day_number"], name="itinerary_item_day_idx"),
                    models.Index(fields=["booking_id"], name="itinerary_item_booking_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("itinerary", "day_number", "sequence_no"),
                        name="itinerary_item_position_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gte", models.F("starts_at"))),
                        name="itinerary_item_ends_after_it_starts",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("day_number__gte", 1), ("sequence_no__gte", 1)),
                        name="itinerary_item_position_is_one_based",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("item_type", "STAY"), _negated=True),
                            models.Q(
                                models.Q(
                                    models.Q(
                                        ("accommodation_id__isnull", False),
                                        ("location_point__isnull", True),
                                    ),
                                    models.Q(
                                        ("accommodation_id__isnull", True),
                                        ("location_point__isnull", False),
                                    ),
                                    _connector="OR",
                                ),
                                ("activity_departure_id__isnull", True),
                                ("activity_id__isnull", True),
                                ("attraction_id__isnull", True),
                                ("booking_id__isnull", True),
                                ("currency__isnull", True),
                                ("line_total__isnull", True),
                                ("origin_destination_id__isnull", True),
                                ("target_destination_id__isnull", True),
                                ("unit_price__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="itinerary_item_stay_is_an_anchor",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("item_type", "ACTIVITY"), _negated=True),
                            models.Q(
                                ("accommodation_id__isnull", True),
                                ("activity_id__isnull", False),
                                ("attraction_id__isnull", True),
                                ("location_point__isnull", True),
                                ("origin_destination_id__isnull", True),
                                ("target_destination_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="itinerary_item_activity_names_an_activity",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("item_type", "ATTRACTION"), _negated=True),
                            models.Q(
                                ("accommodation_id__isnull", True),
                                ("activity_departure_id__isnull", True),
                                ("activity_id__isnull", True),
                                ("attraction_id__isnull", False),
                                ("location_point__isnull", True),
                                ("origin_destination_id__isnull", True),
                                ("target_destination_id__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="itinerary_item_attraction_names_an_attraction",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("item_type", "TRANSFER"), _negated=True),
                            models.Q(
                                ("accommodation_id__isnull", True),
                                ("activity_departure_id__isnull", True),
                                ("activity_id__isnull", True),
                                ("attraction_id__isnull", True),
                                ("distance_m__isnull", False),
                                ("estimate_quality__isnull", False),
                                ("location_point__isnull", True),
                                ("origin_point__isnull", False),
                                ("target_point__isnull", False),
                                ("travel_seconds__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="itinerary_item_transfer_has_endpoints_and_provenance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("item_type", "FREE_TIME"), _negated=True),
                            models.Q(
                                ("accommodation_id__isnull", True),
                                ("activity_departure_id__isnull", True),
                                ("activity_id__isnull", True),
                                ("attraction_id__isnull", True),
                                ("currency__isnull", True),
                                ("line_total__isnull", True),
                                ("location_point__isnull", True),
                                ("origin_destination_id__isnull", True),
                                ("target_destination_id__isnull", True),
                                ("unit_price__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="itinerary_item_free_time_references_nothing",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("item_type", "TRANSFER"),
                            ("estimate_quality__isnull", True),
                            _connector="OR",
                        ),
                        name="itinerary_item_only_transfers_carry_provenance",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("line_total__isnull", True), ("unit_price__isnull", True)),
                            ("currency__isnull", False),
                            _connector="OR",
                        ),
                        name="itinerary_item_money_carries_its_currency",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="itinerary",
            constraint=models.CheckConstraint(
                condition=models.Q(("version__gte", 1)), name="itinerary_version_starts_at_one"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripflight",
            constraint=models.UniqueConstraint(
                fields=("trip", "direction"), name="trip_flight_one_per_direction"
            ),
        ),
        migrations.AddConstraint(
            model_name="tripflight",
            constraint=models.CheckConstraint(
                condition=models.Q(("pax_count__gte", 1)),
                name="trip_flight_carries_at_least_one_passenger",
            ),
        ),
        *[attach_updated_at_trigger(table) for table in TABLES],
        migrations.RunSQL(sql=FOREIGN_KEYS, reverse_sql=DROP_FOREIGN_KEYS),
    ]
