"""§10.8's `itinerary_item_archive` — the previous version's items.

Lands with the code that writes it. `generate_itinerary` archives the rows it
is about to replace, so this table has a writer from its first migration rather
than waiting for one — which is the failure mode this project has produced
often enough to name.

The cross-module reference columns carry no FOREIGN KEY, unlike the live table.
That is deliberate: §10.8 keeps these rows for dispute investigation, and a key
would let a catalogue row's removal cascade into, or block, the history that
explains what a tourist was shown. `itinerary_item` keeps its keys because it
describes a plan somebody may still act on; this describes one that has already
been superseded.
"""

# Generated by Django 5.1.15 on 2026-08-31 05:39

import django.contrib.gis.db.models.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

from apps.common.db import attach_updated_at_trigger


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItineraryItemArchive",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("version", models.IntegerField()),
                (
                    "archived_at",
                    models.DateTimeField(db_index=True, default=django.utils.timezone.now),
                ),
                ("day_number", models.PositiveSmallIntegerField()),
                ("sequence_no", models.PositiveSmallIntegerField()),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("STAY", "Stay"),
                            ("ACTIVITY", "Activity"),
                            ("TRANSFER", "Transfer"),
                            ("ATTRACTION", "Attraction"),
                            ("FREE_TIME", "Free time"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=160)),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                ("accommodation_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("activity_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "activity_departure_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                ("attraction_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "origin_destination_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "target_destination_id",
                    models.BigIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "location_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "origin_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                (
                    "target_point",
                    django.contrib.gis.db.models.fields.PointField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                ("distance_m", models.IntegerField(blank=True, default=None, null=True)),
                ("travel_seconds", models.IntegerField(blank=True, default=None, null=True)),
                (
                    "estimate_quality",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ROUTED", "Routed"),
                            ("MATRIX", "Matrix"),
                            ("APPROXIMATE", "Approximate"),
                        ],
                        default=None,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("quantity", models.PositiveSmallIntegerField(default=1)),
                (
                    "pax_count",
                    models.PositiveSmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, default=None, max_digits=14, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, default=None, max_length=3, null=True)),
                ("booking_id", models.BigIntegerField(blank=True, default=None, null=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "itinerary",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archived_items",
                        to="trip.itinerary",
                    ),
                ),
            ],
            options={
                "db_table": "itinerary_item_archive",
                "ordering": ["-version", "day_number", "sequence_no"],
                "indexes": [
                    models.Index(
                        fields=["itinerary", "version"], name="itinerary_archive_version_idx"
                    ),
                    models.Index(fields=["archived_at"], name="itinerary_archive_age_idx"),
                ],
            },
        ),
        attach_updated_at_trigger("itinerary_item_archive"),
    ]
