"""The item position constraint is checked at commit, not at each row.

§10.4 line 20 renumbers every item in a day from 1, and applied row by row the
intermediate states collide: moving item B into position 2 while item A still
holds it. An immediately-checked UNIQUE therefore rejects a renumbering whose
result is entirely valid, which is what `generate_itinerary` hit the first time
it rewrote a day.

Deferring checks the state that exists at commit — the state anybody reads. The
rule itself is unchanged: two items may never share a position in a committed
itinerary, and a regeneration that produced one still fails, at COMMIT instead
of at the INSERT.
"""

# Generated by Django 5.1.15 on 2026-08-31 07:53

import django.db.models.constraints
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("trip", "0002_itineraryitemarchive"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="itineraryitem",
            name="itinerary_item_position_unique",
        ),
        migrations.AddConstraint(
            model_name="itineraryitem",
            constraint=models.UniqueConstraint(
                deferrable=django.db.models.constraints.Deferrable["DEFERRED"],
                fields=("itinerary", "day_number", "sequence_no"),
                name="itinerary_item_position_unique",
            ),
        ),
    ]
