# Generated by Django 5.1.15 on 2026-08-18 18:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("entity_type", models.CharField(max_length=64)),
                ("entity_id", models.CharField(blank=True, max_length=64, null=True)),
                ("actor_user_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("actor_role", models.CharField(blank=True, default="", max_length=32)),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("ip", models.GenericIPAddressField(blank=True, null=True)),
                ("request_id", models.CharField(blank=True, default="", max_length=128)),
                ("reason", models.TextField(blank=True, default="")),
            ],
            options={
                "db_table": "audit_log",
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(fields=["entity_type", "entity_id"], name="audit_entity_idx"),
                    models.Index(
                        fields=["actor_user_id", "-occurred_at"], name="audit_actor_time_idx"
                    ),
                    models.Index(fields=["action", "-occurred_at"], name="audit_action_time_idx"),
                ],
            },
        ),
    ]
