"""Dispatch, as two tables — §11.5, §11.7, §7.6, ADR 0029.

`btree_gist` is not created here: `0001_initial` already created it for the
tariff windows, and the exclusion constraint below needs the same extension
for the same reason — PostgreSQL cannot put an equality operator and a range
overlap in one index without it.

`assignment_no_overlapping_work` is §7.6 verbatim, and it is the guarantee
behind §11.6 rule 5 and TC-084. It is partial on the four live statuses: a
completed or abandoned job must stop blocking a driver's diary, or a busy week
would permanently retire them.

`offer_one_live_per_assignment` is the other half of TC-083. §11.5 offers to
one candidate at a time and advances; two open offers would let two drivers
both be told the job is theirs, and the race would be a data error rather than
a contended one.
"""

# Generated by Django 5.1.15 on 2026-09-27 12:30

import uuid

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.transport.models


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DriverAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, editable=False, null=True),
                ),
                ("booking_id", models.BigIntegerField()),
                (
                    "driver_id",
                    models.BigIntegerField(blank=True, db_index=True, default=None, null=True),
                ),
                ("vehicle_id", models.BigIntegerField(blank=True, default=None, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("OFFERED", "Offered"),
                            ("ASSIGNED", "Assigned"),
                            ("EN_ROUTE", "En route"),
                            ("ARRIVED", "Arrived"),
                            ("STARTED", "Started"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                            ("UNFULFILLED", "Unfulfilled"),
                            ("INCIDENT", "Incident"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField()),
                (
                    "pickup_pin_hash",
                    models.CharField(blank=True, default=None, max_length=255, null=True),
                ),
                ("assigned_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("en_route_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("arrived_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("started_at", models.DateTimeField(blank=True, default=None, null=True)),
                ("completed_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "override_reason",
                    models.CharField(blank=True, default=None, max_length=200, null=True),
                ),
                (
                    "cancellation_reason",
                    models.CharField(blank=True, default=None, max_length=200, null=True),
                ),
                (
                    "incident_reason",
                    models.CharField(blank=True, default=None, max_length=200, null=True),
                ),
                ("version", models.IntegerField(default=0)),
            ],
            options={
                "db_table": "driver_assignment",
                "ordering": ["starts_at", "id"],
                "indexes": [
                    models.Index(fields=["status", "starts_at"], name="assignment_due_idx"),
                    models.Index(fields=["booking_id"], name="assignment_booking_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("deleted_at__isnull", True)),
                        fields=("booking_id",),
                        name="assignment_one_per_booking_alive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                [
                                    "PENDING",
                                    "OFFERED",
                                    "ASSIGNED",
                                    "EN_ROUTE",
                                    "ARRIVED",
                                    "STARTED",
                                    "COMPLETED",
                                    "CANCELLED",
                                    "UNFULFILLED",
                                    "INCIDENT",
                                ],
                            )
                        ),
                        name="assignment_status_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("ends_at__gt", models.F("starts_at"))),
                        name="assignment_window_is_forwards",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("driver_id__isnull", True), ("vehicle_id__isnull", True)),
                            models.Q(("driver_id__isnull", False), ("vehicle_id__isnull", False)),
                            _connector="OR",
                        ),
                        name="assignment_driver_and_vehicle_together",
                    ),
                    django.contrib.postgres.constraints.ExclusionConstraint(
                        condition=models.Q(
                            ("deleted_at__isnull", True),
                            ("status__in", ("ASSIGNED", "EN_ROUTE", "ARRIVED", "STARTED")),
                        ),
                        expressions=[
                            ("driver_id", "="),
                            (
                                apps.transport.models.TsRange(
                                    "starts_at",
                                    "ends_at",
                                    django.contrib.postgres.fields.ranges.RangeBoundary(),
                                ),
                                "&&",
                            ),
                        ],
                        name="assignment_no_overlapping_work",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DriverOffer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("driver_id", models.BigIntegerField(db_index=True)),
                ("vehicle_id", models.BigIntegerField()),
                ("rank", models.SmallIntegerField()),
                ("score", models.DecimalField(decimal_places=5, max_digits=6)),
                ("score_components", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SENT", "Sent"),
                            ("ACCEPTED", "Accepted"),
                            ("DECLINED", "Declined"),
                            ("EXPIRED", "Expired"),
                            ("SUPERSEDED", "Superseded"),
                        ],
                        default="SENT",
                        max_length=20,
                    ),
                ),
                ("expires_at", models.DateTimeField()),
                ("responded_at", models.DateTimeField(blank=True, default=None, null=True)),
                (
                    "decline_reason",
                    models.CharField(blank=True, default=None, max_length=200, null=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assignment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offers",
                        to="transport.driverassignment",
                    ),
                ),
            ],
            options={
                "db_table": "driver_offer",
                "ordering": ["assignment_id", "rank", "id"],
                "indexes": [
                    models.Index(fields=["status", "expires_at"], name="offer_expiry_sweep_idx"),
                    models.Index(fields=["driver_id", "status"], name="offer_driver_idx"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "SENT")),
                        fields=("assignment",),
                        name="offer_one_live_per_assignment",
                    ),
                    models.UniqueConstraint(
                        fields=("assignment", "driver_id"),
                        name="offer_one_per_driver_per_assignment",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "status__in",
                                ["SENT", "ACCEPTED", "DECLINED", "EXPIRED", "SUPERSEDED"],
                            )
                        ),
                        name="offer_status_known",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rank__gte", 1)), name="offer_rank_is_a_place"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("score__gte", 0), ("score__lte", 1)),
                        name="offer_score_is_a_fraction",
                    ),
                ],
            },
        ),
    ]
