"""The two points §11.7's guards are measured from — ADR 0029.

Snapshotted onto the assignment because both centres live on
`booking_transfer`, and §6.4 forbids `transport -> booking`. Without them,
§11.7's machine would live here and the thing that enforces its geofence guard
would have to live somewhere that can read a booking — the guard and the
machine in two different modules, which is how one of them quietly stops
matching the other.

Nullable, because the two tables created in `0002` may already hold rows by the
time this runs. An assignment with no centre recorded cannot be judged against
a geofence, and the service treats that as requiring an override rather than as
permission — a missing fence is not an open gate.
"""

# Generated by Django 5.1.15 on 2026-09-27 17:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("transport", "0002_assignment_and_offer"),
    ]

    operations = [
        migrations.AddField(
            model_name="driverassignment",
            name="dropoff_point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, geography=True, null=True, srid=4326
            ),
        ),
        migrations.AddField(
            model_name="driverassignment",
            name="pickup_point",
            field=django.contrib.gis.db.models.fields.PointField(
                default=None, geography=True, null=True, srid=4326
            ),
        ),
    ]
