# Generated by Django 5.1.15 on 2026-08-18 18:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IdempotencyRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                ("key", models.CharField(max_length=64)),
                ("endpoint", models.CharField(max_length=200)),
                ("principal_id", models.BigIntegerField(blank=True, null=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("response_status", models.PositiveSmallIntegerField()),
                ("response_body", models.JSONField()),
                ("expires_at", models.DateTimeField(db_index=True)),
            ],
            options={
                "db_table": "idempotency_record",
                "indexes": [models.Index(fields=["expires_at"], name="idx_idempotency_expiry")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "endpoint", "principal_id"),
                        name="uniq_idempotency_key_scope",
                    )
                ],
            },
        ),
    ]
