"""Who may drive, and what they drive — §7.5.4, §7.5.5, ADR 0029.

The only two dispatch tables the SRS specifies column for column, so this
migration invents nothing. What ADR 0029 decides about them is small and
recorded there: `home_destination_id` is NOT NULL because §11.6's scoring
anchor falls back to it, and `licence_number` and `national_id_ref` are BYTEA
rather than text because §30.4 names both columns for envelope encryption.

Both unique indexes are partial on `deleted_at IS NULL`, so a closed account
does not permanently reserve a national identity number or a number plate.
"""

# Generated by Django 5.1.15 on 2026-09-27 12:03

import uuid
from decimal import Decimal

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.provider.models


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Driver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, editable=False, null=True),
                ),
                ("user_id", models.BigIntegerField()),
                ("licence_number", models.BinaryField()),
                ("licence_expires_on", models.DateField()),
                ("national_id_ref", models.BinaryField(blank=True, default=None, null=True)),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_online", models.BooleanField(default=False)),
                (
                    "service_area",
                    django.contrib.gis.db.models.fields.PolygonField(
                        blank=True, default=None, geography=True, null=True, srid=4326
                    ),
                ),
                ("home_destination_id", models.BigIntegerField(db_index=True)),
                (
                    "languages",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=10),
                        default=apps.provider.models._english,
                        size=None,
                    ),
                ),
                (
                    "rating_avg",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("5")),
                        ],
                    ),
                ),
                (
                    "acceptance_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("100.00"),
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0")),
                            django.core.validators.MaxValueValidator(Decimal("100")),
                        ],
                    ),
                ),
                ("completed_trips", models.IntegerField(default=0)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="drivers",
                        to="provider.provider",
                    ),
                ),
            ],
            options={
                "db_table": "driver",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now, editable=False
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(default=django.utils.timezone.now, editable=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, default=None, editable=False, null=True),
                ),
                ("plate_number", models.CharField(max_length=20)),
                ("make", models.CharField(max_length=40)),
                ("model", models.CharField(max_length=40)),
                ("year", models.SmallIntegerField()),
                ("colour", models.CharField(max_length=20)),
                ("seat_capacity", models.SmallIntegerField()),
                ("luggage_capacity", models.SmallIntegerField()),
                (
                    "vehicle_class",
                    models.CharField(
                        choices=[
                            ("STANDARD", "Standard"),
                            ("COMFORT", "Comfort"),
                            ("VAN", "Van"),
                            ("MINIBUS", "Minibus"),
                        ],
                        default="STANDARD",
                        max_length=20,
                    ),
                ),
                ("has_air_conditioning", models.BooleanField(default=True)),
                ("insurance_expires_on", models.DateField()),
                ("inspection_expires_on", models.DateField()),
                (
                    "verify_status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SUBMITTED", "Submitted"),
                            ("UNDER_REVIEW", "Under review"),
                            ("VERIFIED", "Verified"),
                            ("REJECTED", "Rejected"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "driver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="provider.driver",
                    ),
                ),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="vehicles",
                        to="provider.provider",
                    ),
                ),
            ],
            options={
                "db_table": "vehicle",
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(
                fields=["verify_status", "is_online"], name="driver_dispatchable_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="driver",
            index=models.Index(fields=["provider"], name="driver_provider_idx"),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("user_id",),
                name="driver_user_unique_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verify_status__in",
                        ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "VERIFIED", "REJECTED", "SUSPENDED"],
                    )
                ),
                name="driver_verify_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="driver",
            constraint=models.CheckConstraint(
                condition=models.Q(("completed_trips__gte", 0)),
                name="driver_completed_trips_non_negative",
            ),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["driver", "is_active"], name="vehicle_driver_active_idx"),
        ),
        migrations.AddIndex(
            model_name="vehicle",
            index=models.Index(fields=["vehicle_class"], name="vehicle_class_idx"),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted_at__isnull", True)),
                fields=("plate_number",),
                name="vehicle_plate_unique_alive",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("vehicle_class__in", ["STANDARD", "COMFORT", "VAN", "MINIBUS"])
                ),
                name="vehicle_class_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "verify_status__in",
                        ["DRAFT", "SUBMITTED", "UNDER_REVIEW", "VERIFIED", "REJECTED", "SUSPENDED"],
                    )
                ),
                name="vehicle_verify_status_known",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("seat_capacity__gte", 1), ("luggage_capacity__gte", 0)),
                name="vehicle_capacity_sane",
            ),
        ),
        migrations.AddConstraint(
            model_name="vehicle",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__gte", 1950), ("year__lte", 2100)),
                name="vehicle_year_plausible",
            ),
        ),
    ]
