"""`media` learns where a picture came from — ADR 0018 follow-on.

The table stored a file key, a caption and two dimensions. That is sufficient
for photographs you took and insufficient for any that you did not:
attribution is a *condition* of CC BY, so an image under that licence could
not lawfully be displayed by this schema at all, because there was nowhere to
put the credit.

Purely additive — every existing row is own work, `license_code = ''`, which
the constraint exempts. Nothing to backfill.
"""

# Generated by Django 5.1.15 on 2026-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0008_market_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="media",
            name="attribution",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="media",
            name="license_code",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AddField(
            model_name="media",
            name="license_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="media",
            name="source_url",
            field=models.URLField(blank=True, default="", max_length=500),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("license_code", ""),
                    models.Q(
                        models.Q(("attribution", ""), _negated=True),
                        models.Q(("license_url", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="media_licensed_rows_carry_attribution",
            ),
        ),
    ]
