# Generated by Django 5.1.15 on 2026-08-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalogue", "0009_media_attribution"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="owner_type",
            field=models.CharField(
                choices=[
                    ("market", "Market"),
                    ("destination", "Destination"),
                    ("attraction", "Attraction"),
                    ("activity", "Activity"),
                    ("accommodation", "Accommodation"),
                    ("room_type", "Room type"),
                ],
                max_length=20,
            ),
        ),
    ]
